import { fileURLToPath } from "node:url";

import { defineConfig } from "vitest/config";

// Root Vitest config (ADR-0011 §7): monorepo runs use `test.projects`, NOT the
// deprecated vitest.workspace.ts. The tree is split into per-package projects
// (domain, format, data, ui) plus `admin` for the apps/admin/src tree. The
// `server-only`→empty-stub alias lives with the @gym/data project — its ./server
// DAL keeps the `import 'server-only'` poison-pill, exercised via the supabase-fake.
export default defineConfig({
  test: {
    // Coverage is a ROOT-level concern (vitest ignores per-project `coverage`),
    // and it is read by `pnpm test:coverage` only — never by `pnpm test`, so the
    // pre-commit hook (lint && typecheck && test) stays fast and ungated.
    //
    // `include` is EXPLICIT and load-bearing. Vitest's default is "only files
    // covered by tests", which would make an untested file invisible to the
    // report — the suite would read 100% while never touching it. Listing the
    // tree instead means an uncovered file shows up as 0%, not as absent.
    //
    // The denominator is the LOGIC tier: `.ts` only. The 95 `.tsx` components and
    // the Next.js page/layout tree are out of scope by construction (no `.tsx`
    // glob here) — this repo has no DOM test infra (no jsdom, no testing-library)
    // and every project below runs `environment: "node"`. Adding component
    // coverage is a separate decision, not a silent side effect of this config.
    //
    // NOTE: 100% here is NOT "the database is covered". `packages/data` mocks the
    // RPC boundary, so the 25 write RPCs are invisible to vitest by design — their
    // real contract is proven by `pnpm test:denial` (see AGENTS.md).
    coverage: {
      provider: "v8",
      include: [
        "packages/*/src/**/*.ts",
        "packages/domain/**/*.ts",
        "apps/*/src/**/*.ts",
        "supabase/functions/**/*.ts",
        "tools/guards/**/*.ts",
      ],
      exclude: [
        "**/*.test.ts",
        "**/*.d.ts",
        // Out of scope, and stated as an exclusion rather than merely left out of
        // `include`: a `.tsx` component pulled in transitively by a `.ts` test (the
        // ui geometry tests import their components) is otherwise reported as a
        // loaded file, dragging 95 untestable-here components into the denominator.
        // `exclude` is the authoritative gate; `include` alone does not hold them out.
        "**/*.tsx",
        // Generated by the Supabase CLI: 1681 lines of pure type declarations whose
        // only runtime export is a `Constants` enum object. A test here asserts a
        // generated constant equals itself — it moves the number, not the risk.
        "packages/data/src/database.types.ts",
        // The Deno shell of the Send Email Hook: imports Deno APIs, so it cannot
        // load under the node environment. Already excluded from tsc + eslint for
        // the same reason; its pure decision core (`correo.ts`) IS covered.
        "supabase/functions/**/index.ts",
      ],
      reporter: ["text", "json-summary", "html"],
      // The loop's stop condition: `pnpm test:coverage` exits non-zero until every
      // statement, branch, function, and line in the include set is covered.
      thresholds: { 100: true },
      // Still emit the report when a test fails, so a red run is diagnosable.
      reportOnFailure: true,
    },
    projects: [
      {
        // @gym/domain — pure rules + types, no aliases (relative imports, no
        // server-only). Its co-located rules.test.ts moved with the package.
        test: {
          name: "domain",
          environment: "node",
          include: ["packages/domain/**/*.test.ts"],
        },
      },
      {
        // @gym/format — pure leaf (es-MX / Chihuahua-tz formatters). No `@`
        // alias and no `server-only` stub: it imports nothing internal.
        test: {
          name: "format",
          environment: "node",
          include: ["packages/format/src/**/*.test.ts"],
        },
      },
      {
        // @gym/data — the server-only DAL + export/ + Supabase clients (ADR-0011
        // §5/§7). Each ./server module keeps `import 'server-only'`; the unit tests
        // inject the supabase-fake, so stub that runtime guard with the package's
        // own empty module. No `@` alias — the package uses relative + @gym/*
        // specifiers only.
        test: {
          name: "data",
          environment: "node",
          include: ["packages/data/**/*.test.ts"],
        },
        resolve: {
          alias: {
            "server-only": fileURLToPath(
              new URL(
                "./packages/data/node_modules/server-only/empty.js",
                import.meta.url,
              ),
            ),
          },
        },
      },
      {
        // @gym/ui — forge kit + motion/utils/viewport. Tests cover pure logic
        // (countUpStep, flipDelta, skeletonStyle, keyboardInset, the clases-picker
        // geometry, prefersReducedMotion via a stubbed matchMedia), so node env is
        // enough. Internal imports are relative; @gym/domain resolves via the
        // workspace, so no aliases.
        test: {
          name: "ui",
          environment: "node",
          include: ["packages/ui/**/*.test.ts"],
        },
      },
      {
        // @gym/brand — the two brand modules + the registry. The registry test
        // references (never renders) the logo/animation components, so node env is
        // enough; no aliases (imports are relative + `react` type-only).
        test: {
          name: "brand",
          environment: "node",
          include: ["packages/brand/**/*.test.ts"],
        },
      },
      {
        // apps/admin — app-local utils (auth/nav/swipe) plus the vender receipt
        // send seam (recibo-envio.test.ts). After the @/* alias was deleted (the
        // boundary cutover), every app import resolves via @gym/* workspace
        // specifiers or relative paths. The recibo-envio test pulls the @gym/data
        // ./server modules (recibo-mail), which keep the `import 'server-only'`
        // poison-pill, so stub that runtime guard with the same empty module the
        // @gym/data project uses — nothing calls createClient when a transport is
        // injected, so loading the chain is enough.
        test: {
          name: "admin",
          environment: "node",
          include: ["apps/admin/src/**/*.test.ts"],
        },
        resolve: {
          alias: {
            "server-only": fileURLToPath(
              new URL(
                "./packages/data/node_modules/server-only/empty.js",
                import.meta.url,
              ),
            ),
          },
        },
      },
      {
        // apps/client — the socio's panel: app-local pure logic (auth-form
        // validation) plus the server-only Turnstile captcha verifier that guards
        // the public writes (contact-form intake + registration). Node env; the
        // verifier keeps the `import 'server-only'` poison-pill (it holds the
        // captcha secret), stubbed via the same empty module the @gym/data project
        // uses.
        test: {
          name: "client",
          environment: "node",
          include: ["apps/client/src/**/*.test.ts"],
        },
        resolve: {
          alias: {
            "server-only": fileURLToPath(
              new URL(
                "./packages/data/node_modules/server-only/empty.js",
                import.meta.url,
              ),
            ),
          },
        },
      },
      {
        // supabase/functions — the Send Email Hook's pure decision core (#75).
        // `correo.ts` has zero imports and no Deno APIs, so node env covers it; the
        // Deno shell `index.ts` is excluded from tsc/eslint and carries no test.
        test: {
          name: "hooks",
          environment: "node",
          include: ["supabase/functions/**/*.test.ts"],
        },
      },
      {
        // Repo-structure guards (audit 2026-06-30): manifest/catalog consistency,
        // turbo-task implementation, docs-as-tests, public-asset orphans, and the
        // client→server seam convention. Pure fs reads, node env, no aliases.
        test: {
          name: "guards",
          environment: "node",
          include: ["tools/guards/**/*.test.ts"],
        },
      },
    ],
  },
});
