import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

/**
 * Capture the running local Supabase stack's connection details into the file the
 * harness reads (config.useLocalDatabase). Run this once after `supabase start`, and
 * again any time you `supabase stop && supabase start` — the keys are stable, but the
 * file must exist for PERF_DB=local to run at all.
 *
 * Written from Node rather than shelling `supabase status -o env > file`, because on
 * Windows a PowerShell redirect writes UTF-16 and the parser would choke on it.
 */
const out = execFileSync("supabase", ["status", "-o", "env"], {
  encoding: "utf8",
  shell: true,
});

// `supabase status` names them API_URL / ANON_KEY / SERVICE_ROLE_KEY; the apps want the
// NEXT_PUBLIC_* names, and the seed script wants the service-role key.
const get = (key) => out.match(new RegExp(`^${key}="?(.*?)"?$`, "m"))?.[1];

const url = get("API_URL");
const anon = get("ANON_KEY");
const service = get("SERVICE_ROLE_KEY");

if (!url || !anon || !service) {
  console.error("could not parse `supabase status` — is the local stack running?\n");
  console.error(out);
  process.exit(1);
}

writeFileSync(
  "tools/perf/.env.local-db",
  [
    "# Generated by `pnpm perf:env` from the running local Supabase stack.",
    "# Local-only demo keys — machine-local, not committed, not secret.",
    `NEXT_PUBLIC_SUPABASE_URL=${url}`,
    `NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${anon}`,
    `SUPABASE_SERVICE_ROLE_KEY=${service}`,
    // The app refuses to start without this (D2 tenant binding, issue #93). Any value
    // works locally as long as it MATCHES the `tenant_assertion_key` the seed puts in
    // the local Vault — see seed-local.mjs.
    "TENANT_ASSERTION_KEY=perf-local-tenant-assertion-key",
    "",
  ].join("\n"),
  "utf8",
);

console.log(`local Supabase captured: ${url}`);
